---
--- Generated by Luanalysis
--- Created by 肖江辉.
--- DateTime: 2023/3/20 20:57
---
if (redis.call('exists', KEY[1]) == 0) then
    redis.call('hset',KEY[1],ARGV[1],1)
    redis.call('expire',KEY[1],ARGV[2])
    return 1
end
if (redis.call('hexists', KEY[1], ARGV[1]) == 1) then
    redis.call('hincrby',KEY[1],ARGV[1],1)
    redis.call('expire',KEY[1],ARGV[2])
    return 1
end
return 0