---
--- Generated by Luanalysis
--- Created by 肖江辉.
--- DateTime: 2023/3/19 4:01
---
-- 这里的 KEYS[1] 就是锁的key，这里的ARGV[1] 就是当前线程标示
local key =KEYS[1]
local threadId=ARGV[1]
-- 获取锁中的标示，判断是否与当前线程标示一致
if (redis.call('get',key)==threadId) then
    -- 一致，删除锁
    return redis.call('del',key)
end
-- 不一致，返回0
return 0